--- PPPP  EEEEE RRRR  M   M III  SSSS  SSSS III  OOO  N   N  SSSS
--- P   P E     R   R MM MM  I  S     S      I  O   O NN  N S
--- PPPP  EEEE  RRRR  M M M  I   SSS   SSS   I  O   O N N N  SSS
--- P     E     R  R  M   M  I      S     S  I  O   O N  NN     S
--- P     EEEEE R   R M   M III SSSS  SSSS  III  OOO  N   N SSSS
---
