# H   H PPPP  Y   Y RRRR  PPPP    A   PPPP  EEEEE RRRR  
# H   H P   P  Y Y  R   R P   P  A A  P   P E     R   R 
# HHHHH PPPP    Y   RRRR  PPPP  AAAAA PPPP  EEEE  RRRR  
# H   H P       Y   R  R  P     A   A P     E     R  R  
# H   H P       Y   R   R P     A   A P     EEEEE R   R 
#                                                       


preload = $HOME/.config/hypr/wallpapers/gruvbox-wallpapers/wallpapers/irl/village.jpg

wallpaper = ,$HOME/.config/hypr/wallpapers/gruvbox-wallpapers/wallpapers/irl/village.jpg

# Showing something while it loads
splash = false
